### PR TITLE
Refactoring regular expression code

### PR DESCRIPTION
**Pull request by heypano**
Hey there -- I am trying to add a feature (node background color via #123abc) and in the process of doing that I ended up refactoring some of the regular expression code so that it is all contained in one method and does not depend on if/elses

I hope this helps and if it does let me know if I can make it better / have any questions.

Thanks,
Pano

### CODE REVIEW

**Comment by rob-gordon** [comment]
@heypano This PR looks great. I had it in my mind to do something similar for a while, but I don't think I would have done it as cleanly.

My goal for this week was to add some tests to make sure the parsing logic does what it's supposed to. After that maybe we could rebase this PR over that just to make sure that it still passes all tests, and then it's good to merge.

Thanks for opening this!

**Comment by heypano** [comment]
@rob-gordon Thank you! Sounds good - will rebase once the tests are merged
Is it OK if I open a new issue to discuss the color feature I want to add?

**Comment by rob-gordon** [comment]
@heypano Tests are merged 👍

**Comment by heypano** [comment]
@rob-gordon 2 failing tests fixed! (had forgotten to trim labels)

**Comment by heypano** [comment]
Although looks like the overall test action is failing with "Could not find a repository, try using upload token" -- not sure how to address that but seems unrelated to the actual tests

**Comment by rob-gordon** [comment]
@heypano Ok, I'll check it out. Glad the tests helped catch something!

**Review by rob-gordon — APPROVED** [review]
I'm sure the Test action is failing because I misconfigured something with Codecov.

Thanks for this PR. It's a really nice step in the right direction.

It actually got me thinking, I bet we could create an array of `getLineData()`'s for each line once before parsing, and then just reference array indexes all throughout parsing and the nested loops.

Performance is definitely not a big problem, but it could be a cool future improvement 🤷‍♂️

Thanks again! Feel free to merge whenever

**Comment by heypano** [comment]
Thank you @rob-gordon  !! I am glad it is helpful!

I don't have merge permissions so I think you'd have to do the merge

I will have another PR for a color feature soon :)

**Comment by rob-gordon** [comment]
> I will have another PR for a color feature soon :)

@heypano If it's a significant change or UI-change it may be worth opening a discussion first. I have some near-term plans for adding features and UI to support, so I wouldn't want it to conflict.

**Comment by heypano** [comment]
OK will do, thanks!

**Pull request merged**
